# Generated by Django 4.0.2 on 2022-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_lrmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANN_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.BinaryField()),
            ],
        ),
    ]
