# Generated by Django 4.0.2 on 2022-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_ann_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Alogorithm', models.CharField(default='ann', max_length=500)),
            ],
        ),
    ]
