# Generated by Django 4.0.2 on 2022-06-05 02:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_site', '0004_page_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='username')),
                ('Full_Name', models.CharField(default='', max_length=500)),
                ('Phone_Number', models.CharField(default='', max_length=14)),
                ('Date', models.DateField(default=datetime.datetime(2022, 6, 5, 2, 38, 50, 946026, tzinfo=utc))),
                ('Profile_Picture', models.ImageField(default='default.png', upload_to='user_pics')),
                ('Contributions', models.IntegerField(default=0)),
                ('Status', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
